int _putchar(char c);
void alphabet(void);
void alphabet_x10(void);
int _islower(int c);
int _isalpha(int c);
int print_sign(int n);
int _abs(int);
int add(int, int);
int print_last_digit(int);
void print_to_98(int n);
void jack_bauer(void);
